arch = [
    "yazi",
    "bat",
    "fastfetch",
    "man-db",
    "jq",
    "unzip",
    "ripgrep",
    "fzy",
    "playerctl",
    "reflector",
    "peaclock",
    "libqalculate",
    "yt-dlp",
    "7zip"
]
