#!/usr/bin/env bash

# TODO: Make it so that the service are only enabled if the package is installed

sudo systemctl enable lemurs.service

systemctl enable --user --now pipewire.service
systemctl enable --user --now pipewire-pulse.service
systemctl enable --user --now wireplumber.service

systemctl --user add-wants niri.service plasma-polkit-agent.service
systemctl --user add-wants niri.service swww.service
systemctl --user add-wants niri.service swaync.service
systemctl --user add-wants niri.service swayidle.service
systemctl --user add-wants niri.service xdg-desktop-portal.service
systemctl --user add-wants niri.service xdg-desktop-portal-gnome.service

systemctl --user add-wants niri.service eww.service

echo "Services have been setup."
