#!/usr/bin/env bash

swww img \
    --transition-step 255 \
    --transition-duration 0.5 \
    --transition-type grow \
    --transition-pos top-right \
    --transition-angle 30 \
    --transition-fps 60 \
    $1
