#!/usr/bin/env bash

scripts_directory=~/.scripts/desktop-environment
preview_wallpaper=$1
original_wallpaper=$2

fade_wallpaper() {
    swww img \
        --transition-step 20 \
        --transition-duration 0.1 \
        --transition-type simple \
        --transition-fps 60 \
        $1
}

if [ -d "$preview_wallpaper" ]; then
    fade_wallpaper "$original_wallpaper"
else
    fade_wallpaper "$preview_wallpaper"
fi
