syntax = "Lua51"
column_width = 80
line_endings = "Unix"
indent_type = "Spaces"
indent_width  = 4
quote_style = "AutoPreferDouble"
call_parentheses = "Always"
space_after_function_names = "Never"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
